name: Main Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      python-version: '3.11'

  
  docker-build:
    needs: ci                          
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image-name: ${{ github.repository }}
      tag: ${{ github.sha }}
      push: ${{ github.ref == 'refs/heads/main' }}  
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
